[package]
name = "mpfr"
version = "0.0.8"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
description = "High-level bindings to MPFR library"
license = "MIT"
repository = "https://github.com/netvl/mpfr.rs"

[dependencies]
mpfr-sys = "*"
bitflags = "*"
num = "*"

